### PR TITLE
Remove locale files and refactor providers

### PR DESCRIPTION
**Pull request by BenBornschein**
Deleted locale files for various services and refactored the code to use provider-specific classes. Added glossary support for DeepL.

### CODE REVIEW

**Comment by BenBornschein** [comment]
I'm unable to reproduce the error you're experiencing. Please note that an API key is always required for DeepL, even with the free version. Could you provide the specific steps needed to trigger this bulk error in DeepL? The bulk option shown in the screenshot functions correctly on my end.
CleanShot 2024-10-30 at 11 26 41@2x

**Comment by toolstack** [comment]
Is the deepl glossary support the difference between this PR and the previous one?

**Comment by BenBornschein** [comment]
This PR is identical to the previous one. I created a new PR due to issues with my local Git submodule configuration, which caused some problems with Git.
I was able to reproduce the second error you reported, but the reason was a missing DeepL key.

**Comment by toolstack** [comment]
Ok, I found the issue with DeepL, just because there is an API key doesn't mean that you have a paid plan, in which case it means you still use the free api url.

The old code just always used the free-api.deepl.com url.

Probably easiest solution is to just go back to the old behaviour.  Probably best solution would be to add a configuration option for DeepL url toggle.

**Comment by BenBornschein** [comment]
The latest commit fixes this problem. I have also tested it with DeepL Free and DeepL Pro.

**Comment by toolstack** [comment]
Looks good so far, will do some additional testing and if nothing comes up will merge later this week.

**Comment by toolstack** [comment]
I'll do a release in the next day or two.

**Pull request merged**
